language: php
sudo: false
dist: trusty

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

os: linux

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [[ $TRAVIS_PHP_VERSION != 7.2 && $TRAVIS_PHP_VERSION != nightly && $COVERAGE != yes ]]; then phpenv config-rm xdebug.ini; fi
  - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update

install: travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction $COMPOSER_FLAGS -vv

script:
  - composer validate
  - vendor/bin/phpunit --colors --no-coverage

jobs:
  fast_finish: true
  allow_failures:
    - php: 7.2
    - php: nightly
  include:
    - php: 7.2
      env: COMPOSER_FLAGS="--ignore-platform-reqs"
    - php: nightly
      env: COMPOSER_FLAGS="--ignore-platform-reqs"
    - stage: test with coverage
      php: 7.1
      env: 
        - COVERAGE=yes
        - COMPOSER_FLAGS=""
      script: vendor/bin/phpunit --colors --coverage-clover=clover.xml
      after_success:
        - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar && php -n coveralls.phar --verbose --coverage_clover=clover.xml
        - bash <(curl -s https://codecov.io/bash) -f clover.xml -F phpunit
    - stage: check coding style
      php: 7.1
      env: COMPOSER_FLAGS=""
      script: vendor/bin/phpcs
    - stage: check coding style
      php: 7.1
      env: COMPOSER_FLAGS=""
      script: vendor/bin/php-cs-fixer fix --dry-run -vv

notifications:
  email: false
