language: php
sudo: false
dist: trusty

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

os:
  - linux
  #- windows

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""

cache:
  directories:
    - $HOME/.composer/cache

stages:
  - composer validate
  - static code analysis
  - test
  - test with coverage
  - infection

before_install:
  - stty cols 130
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'zend.assertions=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'assert.exception=On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update

install: travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest $COMPOSER_FLAGS -vv

script: vendor/bin/phpunit --colors --columns 117 --no-coverage

jobs:
  allow_failures:
    - php: 7.4snapshot
    - php: nightly
    #- os: windows
  include:
    - php: nightly
      env: COMPOSER_FLAGS="--ignore-platform-reqs"

    - stage: test with coverage
      os: linux
      php: 7.1
      env:
        - COVERAGE=yes
        - COMPOSER_FLAGS=""
      before_install:
        - stty cols 130
        - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - echo 'zend.assertions=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
        - echo 'assert.exception=On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
        - composer self-update
      script: vendor/bin/phpunit --colors --columns 117 --coverage-clover=clover.xml --coverage-text
      after_success:
        - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar && php -n coveralls.phar --verbose --coverage_clover=clover.xml
        - bash <(curl -s https://codecov.io/bash) -f clover.xml -F phpunit

    - stage: composer validate
      os: linux
      php: 7.1
      env: COMPOSER_FLAGS=""
      script:
        - composer validate
        - composer normalize --dry-run

    - stage: static code analysis
      os: linux
      php: 7.1
      env:
        - COMPOSER_FLAGS=""
        - TEST=phpcs
      script: vendor/bin/phpcs --colors

    - stage: static code analysis
      os: linux
      php: 7.1
      env:
        - COMPOSER_FLAGS=""
        - TEST=php-cs-fixer
      script: vendor/bin/php-cs-fixer fix --dry-run -vv

    - stage: static code analysis
      os: linux
      php: 7.1
      env:
        - COMPOSER_FLAGS=""
        - TEST=phpstan
      script: vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=768M --no-progress

    - stage: infection
      os: linux
      php: 7.1
      env:
        - COVERAGE=yes
        - COMPOSER_FLAGS=""
      before_install:
        - stty cols 130
        - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - echo 'zend.assertions=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
        - echo 'assert.exception=On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
        - composer self-update
      script: vendor/bin/infection --min-covered-msi=95 --min-msi=95

notifications:
  email: false
